version: '3.0'
volumes:
  node_modules:

services:
  app:
    image: node:8-alpine
    working_dir: '/app'
    environment:
      LANG: en_US.UTF-8
      FORCE_COLOR: 'true'
    volumes:
      - './:/app/'
      - node_modules:/app/node_modules/
